version: '2'
services:
  web:
    build: docker/nginx
    volumes:
      - .:/app
    ports: 
      - 8080:80
    links:
      - php
    tty: true
    restart: always
  php:
    build: docker/php-fpm
    volumes:
      - .:/app
    working_dir: /app
    links:
      - db
    tty: true
    restart: always
  db:
    image: mysql:latest
    ports:
      - 3360:3306
    volumes:
      - /mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    tty: true
    restart: always
